dist: xenial
language: generic
branches:
  only:
  - source
git:
  depth: false
  quiet: true
before_install:
# - openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  # -in deploy_key.enc -out deploy_key -d
- git config --global user.email "gccll.love@gmail.com"
- git config --global user.name "gcclll"
- git config --global core.quotepath false
- git clone https://github.com/nasfarley88/habash ~/habash
- git clone https://github.com/lujun9972/EGO ~/EGO
- sudo add-apt-repository ppa:ubuntu-elisp/ppa -y
- sudo apt-get update
- sudo apt-get install emacs-snapshot curl jq -y
- emacs-snapshot --version
script:
- git clone https://github.com/lujun9972/csdn-publish.el ~/csdn-publish
- git clone https://github.com/lujun9972/toutiao.el ~/toutiao
- git clone https://github.com/gcclll/zcheng.github.io.git ~/zcheng.github.com
- export REPO="https://github.com/gcclll/zcheng.github.io.git"
- git clone -b source ${REPO} ~/source
- git clone -b master ${REPO} ~/web
- cd ~/source
- cat "deploy_key*" > .gitignore
- emacs-snapshot --batch -l ./auto_publish.el
- "./generate_index.sh >README.org"
- git commit -a -m "[skip travis] update README" || true
- git push origin source
- ~/habash/habash up "写博客"
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: "/home/travis/web"
  target_branch: master
  on:
    branch:
    - source
